# Generated by Django 5.2.6 on 2025-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stocks', models.IntegerField()),
                ('rarity', models.IntegerField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('hat', 'Hat'), ('merchandise', 'Merchandise'), ('ball', 'Ball'), ('handsign', 'Hansign'), ('shoes', 'Shoes')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
