# Generated by Django 5.2.6 on 2025-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_employee_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
