# Generated by Django 5.2.6 on 2025-10-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
